server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@192.168.2.204:8000/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@192.168.2.205:8000/eureka/